import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const helper = fileURLToPath(new URL('./helpers/logging-process.mjs', import.meta.url));

async function assertGeneratedTempDir(dir) {
  const root = resolve(await realpath(tmpdir())), target = resolve(await realpath(dir)), rel = relative(root, target);
  assert.notEqual(target, root, 'cleanup target must not be the temporary root');
  assert.ok(!isAbsolute(rel) && rel !== '..' && !rel.startsWith(`..${sep}`), 'cleanup target must stay below the temporary root');
  assert.ok(basename(target).startsWith('logging-process-'), 'cleanup target is generated by this test');
  return target;
}

function start(args) {
  const child = spawn(process.execPath, [helper, ...args], { stdio: ['ignore', 'pipe', 'pipe'] });
  let stdout = '', stderr = '';
  child.stdout.setEncoding('utf8').on('data', chunk => { stdout += chunk; });
  child.stderr.setEncoding('utf8').on('data', chunk => { stderr += chunk; });
  return { child, get stdout() { return stdout; }, get stderr() { return stderr; } };
}

function withTimeout(promise, label, ms = 120000) {
  let timer;
  return Promise.race([promise, new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(`${label} timed out after ${ms}ms`)), ms);
    timer.unref?.();
  })]).finally(() => clearTimeout(timer));
}

async function killChild(proc) {
  if (proc.child.exitCode !== null || proc.child.signalCode !== null) return null;
  const exited = withTimeout(new Promise(resolve => proc.child.once('exit', (code, signal) => resolve({ code, signal }))),
    'logging fixture child exit', 5000);
  assert.equal(proc.child.kill('SIGKILL'), true, 'SIGKILL is sent to the live fixture child');
  return exited;
}

async function waitReady(proc, expected) {
  try {
    await withTimeout(new Promise((resolve, reject) => {
      const check = () => {
        if (proc.stdout.includes(`${expected}\n`)) return resolve();
        if (proc.child.exitCode !== null || proc.child.signalCode !== null)
          return reject(new Error(`fixture child exited early (${proc.child.exitCode ?? proc.child.signalCode}): ${proc.stderr}`));
        setTimeout(check, 10);
      };
      check();
    }), expected);
  } catch (error) {
    await killChild(proc).catch(() => {});
    throw error;
  }
}

async function audit(args) {
  const proc = start(args);
  let exit;
  try {
    exit = await withTimeout(new Promise(resolve => proc.child.once('exit', (code, signal) => resolve({ code, signal }))),
      `audit ${args.join(' ')}`);
  } catch (error) {
    await killChild(proc).catch(() => {});
    throw error;
  }
  assert.deepEqual(exit, { code: 0, signal: null }, `restart audit failed: ${proc.stderr}`);
  try { return JSON.parse(proc.stdout); }
  catch { throw new Error(`restart audit did not emit JSON: ${proc.stdout}\n${proc.stderr}`); }
}

for (const crash of ['before-commit', 'after-commit']) {
  test(`cooperative palm award recovers after SIGKILL ${crash}`, async t => {
    t.diagnostic('File-backed PGlite restart proof for SQL001–016 and GameHost; it does not simulate VM or power loss.');
    const dir = await mkdtemp(join(tmpdir(), 'logging-process-'));
    const dbPath = join(dir, 'db');
    let succeeded = false, fixture = null;
    t.after(async () => {
      if (succeeded) await rm(await assertGeneratedTempDir(dir), { recursive: true, force: true });
      else t.diagnostic(`Retained failed fixture for inspection: ${dir}`);
    });
    try {
      const mode = crash === 'before-commit' ? 'before' : 'after';
      const ready = `READY ${mode} ${crash}`;
      fixture = start([mode, dbPath, crash]);
      await waitReady(fixture, ready);
      assert.equal(fixture.stdout.trim(), ready, 'the initial process reached the requested SQL boundary');
      const terminated = await killChild(fixture);
      assert.equal(terminated.signal, 'SIGKILL', 'no host.close or db.close ran before termination');

      const recovered = await audit(['inspect', dbPath, crash]);
      assert.equal(recovered.mode, 'inspect');
      assert.equal(recovered.replay, crash === 'after-commit');
      assert.equal(recovered.receiptCount, 1, 'retry leaves one M5 receipt');
      assert.equal(recovered.A.progression.practice.logging, 56, 'offline contributor A receives its exact share once');
      assert.equal(recovered.B.progression.practice.logging, 7, 'online contributor B receives its exact share once');
      assert.equal(recovered.A.gold, 137, 'A unrelated profile fields survive recovery');
      assert.equal(recovered.B.gold, 241, 'B unrelated profile fields survive recovery');
      assert.equal(recovered.node.hits, 3, 'the palm final hit is committed exactly once');
      assert.deepEqual(recovered.ledger.contributors, [
        { actor: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', hits: 1 },
        { actor: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', hits: 2 },
      ]);
      if (crash === 'after-commit') assert.deepEqual(recovered.profileVersions, { A: 2, B: 3 });
      succeeded = true;
    } catch (error) {
      if (fixture) await killChild(fixture).catch(() => {});
      throw error;
    }
  });
}
