import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { CRAFT_RECIPES } from '../src/data/resources.js';
import { mkdtemp, realpath, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { basename, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const helper = fileURLToPath(new URL('./helpers/resource-process.mjs', import.meta.url));

async function assertGeneratedTempDir(dir) {
  const root = resolve(await realpath(tmpdir())), target = resolve(await realpath(dir)), rel = relative(root, target);
  assert.notEqual(target, root, 'cleanup target must not be the temporary root');
  assert.ok(!isAbsolute(rel) && rel !== '..' && !rel.startsWith(`..${sep}`), 'cleanup target must stay under the temporary root');
  assert.ok(basename(target).startsWith('resource-process-'), 'cleanup target must be generated by this test');
  return target;
}

function start(args) {
  const child = spawn(process.execPath, [helper, ...args], { stdio: ['ignore', 'pipe', 'pipe'] });
  let stdout = '', stderr = '';
  child.stdout.setEncoding('utf8').on('data', chunk => { stdout += chunk; });
  child.stderr.setEncoding('utf8').on('data', chunk => { stderr += chunk; });
  return { child, get stdout() { return stdout; }, get stderr() { return stderr; } };
}

function withTimeout(promise, label, ms = 120000) {
  let timer;
  return Promise.race([promise, new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(`${label} timed out after ${ms}ms`)), ms);
    timer.unref?.();
  })]).finally(() => clearTimeout(timer));
}

async function killChild(proc, signal = 'SIGKILL') {
  if (proc.child.exitCode !== null || proc.child.signalCode !== null) return null;
  const exited = withTimeout(new Promise(resolve => proc.child.once('exit', (code, childSignal) =>
    resolve({ code, signal: childSignal }))), 'fixture child exit', 5000);
  assert.equal(proc.child.kill(signal), true, `${signal} is sent to the live fixture child`);
  return exited;
}

async function waitReady(proc, expected) {
  try {
    await withTimeout(new Promise((resolve, reject) => {
      const check = () => {
        if (proc.stdout.includes(`${expected}\n`)) return resolve();
        if (proc.child.exitCode !== null || proc.child.signalCode !== null) {
          return reject(new Error(`fixture child exited early (${proc.child.exitCode ?? proc.child.signalCode}): ${proc.stderr}`));
        }
        setTimeout(check, 10);
      };
      check();
    }), expected);
  } catch (error) {
    await killChild(proc).catch(() => {});
    throw error;
  }
}

async function audit(args) {
  const proc = start(args);
  let exit;
  try {
    exit = await withTimeout(new Promise(resolve => proc.child.once('exit', (code, signal) => resolve({ code, signal }))),
      `audit ${args.join(' ')}`);
  } catch (error) {
    await killChild(proc).catch(() => {});
    throw error;
  }
  assert.deepEqual(exit, { code: 0, signal: null }, `restart audit failed: ${proc.stderr}`);
  try { return JSON.parse(proc.stdout); }
  catch { throw new Error(`restart audit did not emit JSON: ${proc.stdout}\n${proc.stderr}`); }
}

for (const operation of ['gather', 'craft']) for (const crash of ['before-commit', 'after-commit']) {
  test(`${operation} resource operation recovers after SIGKILL ${crash}`, async t => {
    t.diagnostic('File-backed PGlite restart proof for SQL001–015 and GameHost; it does not simulate VM or power loss.');
    const dir = await mkdtemp(join(tmpdir(), 'resource-process-'));
    const dbPath = join(dir, 'db');
    let succeeded = false, fixture = null;
    t.after(async () => {
      if (succeeded) await rm(await assertGeneratedTempDir(dir), { recursive: true, force: true });
      else t.diagnostic(`Retained failed fixture for inspection: ${dir}`);
    });
    try {
      const mode = crash === 'before-commit' ? 'before' : 'after';
      const ready = `READY ${mode} ${operation} ${crash}`;
      fixture = start([mode, operation, dbPath, crash]);
      await waitReady(fixture, ready);
      assert.equal(fixture.stdout.trim(), ready, 'the first process reached the requested crash boundary');
      const terminated = await killChild(fixture);
      assert.equal(terminated.signal, 'SIGKILL', 'no host.close/db.close ran before the process kill');

      const recovered = await audit(['inspect', operation, dbPath, crash]);
      assert.equal(recovered.mode, 'inspect');
      assert.equal(recovered.operation, operation);
      assert.equal(recovered.replay, crash === 'after-commit');
      assert.equal(recovered.receiptCount, 1, 'recovery or the retry leaves exactly one operation receipt');
      if (operation === 'craft') {
        for (const good of Object.keys(CRAFT_RECIPES.hacha_piedra.inputs))
          assert.equal(recovered.profile.eco.pack.goods[good], undefined, `${good} is consumed exactly once`);
        assert.equal(recovered.tools.axe, 1, 'the durable profile contains the crafted axe');
      } else {
        assert.equal(recovered.profile.eco.pack.goods.tronco, 2, 'gathered tronco was credited once');
        assert.equal(recovered.profile.eco.pack.goods.piedra, 2);
        assert.equal(recovered.tools.axe, 0);
      }
      assert.equal(recovered.profileVersion, 3);
      assert.equal(recovered.worldVersion, 3);
      assert.equal(recovered.replayWhy, '');
      succeeded = true;
    } catch (error) {
      if (fixture) await killChild(fixture).catch(() => {});
      throw error;
    }
  });
}
